### PR TITLE
fix: fix the bug in transforms.md

### PR DESCRIPTION
**Pull request by etheral12138**
#71 fix of issue#71

### CODE REVIEW

**Comment by etheral12138** [comment]
@juanjoDiaz

**Comment by juanjoDiaz** [comment]
Thanks @etheral12138 !

Can you also fix the same typo in `packages/transforms/README.md`?

**Comment by etheral12138** [comment]
I have fix the bug in packages/transforms/README.md,please check it,Thanks! @juanjoDiaz

**Comment by etheral12138** [comment]
@coveralls @jarib @mchelen Please check it,Thanks!

**Pull request merged**
